### ISSUE TITLE
Width and Height seem to be flipped for shelved box

### ISSUE THREAD

**Issue by heschlie** [Wallenstein61/InkScapeBoxMaker#6]
When creating a shelved box it seems that the width and height are flipped.

e.g. when I create a box that is 150mm wide by 150mm deep by 300mm high with 8 shelves I would expect the shelves to be 150mmx150mm and be divided evenly over the 300mm height, what I get is not quite that:

![Screenshot from 2019-06-29 21-29-09](https://user-images.githubusercontent.com/4544262/60392309-fd8a4980-9ab4-11e9-9f71-a31b344e9d37.png)

But when I flip them I get what I expect:

![Screenshot from 2019-06-29 21-30-29](https://user-images.githubusercontent.com/4544262/60392319-23afe980-9ab5-11e9-9723-75dd2d0a4971.png)

Maybe I'm just not following the terminology (new to doing vector stuff) so please close if I'm wrong.

Amazing extension though btw!

**Comment by Michael-Breu-UIbk** [comment]
Hello heschlie,

Sorry, seemed to be on holiday when you posted this issue.

You are right that width and height are flipped. This is due to the fact, that the design is based on an open box, with the opening on top. Where the shelf has its opening to the front.

May be I should make this clear in the configuration dialog.

Wallenstien
